[package]
name = "stone-stark"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3.8.1"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.50"

[dev-dependencies]
rstest = "0.18.2"
